-- Generated by scripts/build-seed.js from data.js — don't edit by hand.
-- Run in the Supabase SQL editor after schema.sql. Safe to re-run: existing
-- people are updated by name, new ones are added.

insert into public.people
  (name, answers, hint, born_year, born_lat, born_lng, born_place, died_year, died_lat, died_lng, died_place)
values
  ('Albert Einstein', array['albert einstein'], 'Physicist and mathematician', 1879, 48.4011, 10.0348, 'Ulm, Germany', 1955, 40.3487, -74.6591, 'Princeton, USA'),
  ('Leonardo da Vinci', array['leonardo da vinci', 'leonardo di ser piero da vinci'], 'Renaissance painter and inventor', 1452, 43.7833, 10.9167, 'Vinci, Italy', 1519, 47.4133, 0.9838, 'Amboise, France'),
  ('Napoleon Bonaparte', array['napoleon bonaparte', 'napoleone buonaparte', 'napoleon i'], 'Military and political leader who crowned himself emperor', 1769, 41.9192, 8.7386, 'Ajaccio, Corsica', 1821, -15.9339, -5.7167, 'Longwood, Saint Helena'),
  ('Marie Curie', array['marie curie', 'marie sklodowska curie', 'maria sklodowska'], 'Scientist who pioneered research on radioactivity', 1867, 52.2297, 21.0122, 'Warsaw, Poland', 1934, 45.9268, 6.7089, 'Passy, France'),
  ('Wolfgang Amadeus Mozart', array['wolfgang amadeus mozart', 'wolfgang mozart', 'amadeus mozart'], 'Composer and child prodigy', 1756, 47.8095, 13.055, 'Salzburg, Austria', 1791, 48.2082, 16.3738, 'Vienna, Austria'),
  ('Vincent van Gogh', array['vincent van gogh'], 'Post-Impressionist painter', 1853, 51.4667, 4.65, 'Zundert, Netherlands', 1890, 49.0667, 2.1667, 'Auvers-sur-Oise, France'),
  ('Nikola Tesla', array['nikola tesla'], 'Inventor and electrical engineer', 1856, 44.6167, 15.3167, 'Smiljan, Croatia', 1943, 40.7128, -74.006, 'New York City, USA'),
  ('Isaac Newton', array['isaac newton'], 'Physicist and mathematician known for the laws of motion', 1643, 52.8055, -0.6297, 'Woolsthorpe, England', 1727, 51.5, -0.1935, 'Kensington, England'),
  ('Abraham Lincoln', array['abraham lincoln'], 'U.S. president during the Civil War', 1809, 37.5679, -85.7378, 'Hodgenville, Kentucky', 1865, 38.8951, -77.0364, 'Washington, D.C.'),
  ('Mahatma Gandhi', array['mahatma gandhi', 'mohandas gandhi', 'mohandas karamchand gandhi', 'mahatma ghandi', 'mohandas ghandi'], 'Leader of a nonviolent independence movement', 1869, 21.6417, 69.6293, 'Porbandar, India', 1948, 28.6139, 77.209, 'New Delhi, India'),
  ('Ludwig van Beethoven', array['ludwig van beethoven', 'ludwig beethoven'], 'Composer who kept writing after losing his hearing', 1770, 50.7374, 7.0982, 'Bonn, Germany', 1827, 48.2082, 16.3738, 'Vienna, Austria'),
  ('Charles Darwin', array['charles darwin'], 'Naturalist known for a theory of evolution', 1809, 52.7069, -2.7538, 'Shrewsbury, England', 1882, 51.3308, 0.0533, 'Downe, England'),
  ('Joan of Arc', array['joan of arc', 'jeanne d''arc'], 'Military leader and religious figure executed in her teens', 1412, 48.4547, 5.6892, 'Domremy, France', 1431, 49.4431, 1.0993, 'Rouen, France'),
  ('Elvis Presley', array['elvis presley', 'elvis aaron presley'], 'Musician known as a rock and roll icon', 1935, 34.2576, -88.7034, 'Tupelo, Mississippi', 1977, 35.1495, -90.049, 'Memphis, Tennessee'),
  ('Anne Frank', array['anne frank', 'annelies frank'], 'Diarist who wrote in hiding during World War II', 1929, 50.1109, 8.6821, 'Frankfurt, Germany', 1945, 52.7594, 9.9114, 'Bergen-Belsen, Germany'),
  ('Frida Kahlo', array['frida kahlo'], 'Painter known for surreal self-portraits', 1907, 19.3467, -99.1618, 'Coyoacan, Mexico City', 1954, 19.355, -99.158, 'Coyoacan, Mexico City')
on conflict (name) do update set
  answers = excluded.answers, hint = excluded.hint,
  born_year = excluded.born_year, born_lat = excluded.born_lat, born_lng = excluded.born_lng, born_place = excluded.born_place,
  died_year = excluded.died_year, died_lat = excluded.died_lat, died_lng = excluded.died_lng, died_place = excluded.died_place;
