// Generates supabase/seed-1.sql, seed-2.sql, … from data.js, so the list of
// people lives in one place. Split into parts so each one pastes comfortably
// into the Supabase SQL editor.
// Usage: node scripts/build-seed.js
const fs = require("fs");
const path = require("path");
const vm = require("vm");

const PER_FILE = 500;
const root = path.join(__dirname, "..");
const dir = path.join(root, "supabase");
const src = fs.readFileSync(path.join(root, "data.js"), "utf8");
const PEOPLE = vm.runInNewContext(src + "\nPEOPLE;");

const q = (s) => "'" + String(s).replace(/'/g, "''") + "'";
const arr = (a) => "array[" + a.map(q).join(", ") + "]::text[]";

const row = (p) =>
  `  (${q(p.name)}, ${arr(p.answers)}, ${q(p.hint)}, ${p.fame || 0}, ${p.wikidata ? q(p.wikidata) : "null"}, ` +
  `${p.born.year}, ${p.born.lat}, ${p.born.lng}, ${q(p.born.place)}, ` +
  `${p.died.year}, ${p.died.lat}, ${p.died.lng}, ${q(p.died.place)})`;

// Remove seed files from earlier runs.
for (const f of fs.readdirSync(dir)) {
  if (/^seed(-\d+)?\.sql$/.test(f)) fs.unlinkSync(path.join(dir, f));
}

const parts = Math.ceil(PEOPLE.length / PER_FILE);
for (let i = 0; i < parts; i++) {
  const chunk = PEOPLE.slice(i * PER_FILE, (i + 1) * PER_FILE);
  const sql = `-- Generated by scripts/build-seed.js from data.js — don't edit by hand.
-- Part ${i + 1} of ${parts} (${chunk.length} people). Run schema.sql first, then every part
-- in the Supabase SQL editor. Safe to re-run: existing people are updated by
-- name, new ones are added.

insert into public.people
  (name, answers, hint, fame, wikidata, born_year, born_lat, born_lng, born_place, died_year, died_lat, died_lng, died_place)
values
${chunk.map(row).join(",\n")}
on conflict (name) do update set
  answers = excluded.answers, hint = excluded.hint, fame = excluded.fame, wikidata = excluded.wikidata,
  born_year = excluded.born_year, born_lat = excluded.born_lat, born_lng = excluded.born_lng, born_place = excluded.born_place,
  died_year = excluded.died_year, died_lat = excluded.died_lat, died_lng = excluded.died_lng, died_place = excluded.died_place;
`;
  fs.writeFileSync(path.join(dir, `seed-${i + 1}.sql`), sql);
}
console.log(`Wrote ${parts} seed file(s) (supabase/seed-1.sql … seed-${parts}.sql) with ${PEOPLE.length} people.`);
