// Generates supabase/seed.sql from data.js, so the list of people lives in one place.
// Usage: node scripts/build-seed.js
const fs = require("fs");
const path = require("path");
const vm = require("vm");

const root = path.join(__dirname, "..");
const src = fs.readFileSync(path.join(root, "data.js"), "utf8");
const PEOPLE = vm.runInNewContext(src + "\nPEOPLE;");

const q = (s) => "'" + String(s).replace(/'/g, "''") + "'";
const arr = (a) => "array[" + a.map(q).join(", ") + "]";

const rows = PEOPLE.map((p) =>
  `  (${q(p.name)}, ${arr(p.answers)}, ${q(p.hint)}, ` +
  `${p.born.year}, ${p.born.lat}, ${p.born.lng}, ${q(p.born.place)}, ` +
  `${p.died.year}, ${p.died.lat}, ${p.died.lng}, ${q(p.died.place)})`
);

const sql = `-- Generated by scripts/build-seed.js from data.js — don't edit by hand.
-- Run in the Supabase SQL editor after schema.sql. Safe to re-run: existing
-- people are updated by name, new ones are added.

insert into public.people
  (name, answers, hint, born_year, born_lat, born_lng, born_place, died_year, died_lat, died_lng, died_place)
values
${rows.join(",\n")}
on conflict (name) do update set
  answers = excluded.answers, hint = excluded.hint,
  born_year = excluded.born_year, born_lat = excluded.born_lat, born_lng = excluded.born_lng, born_place = excluded.born_place,
  died_year = excluded.died_year, died_lat = excluded.died_lat, died_lng = excluded.died_lng, died_place = excluded.died_place;
`;

fs.writeFileSync(path.join(root, "supabase", "seed.sql"), sql);
console.log(`Wrote supabase/seed.sql with ${PEOPLE.length} people.`);
